### ISSUE TITLE
APBioNetTalks: a platform to stream bioinformatics talks, tutorials and trainings

### ISSUE THREAD

**Issue by hzahroh** [open-life-science/ols-2#18]
Project Lead: Hilyatuz Zahroh <hzahroh>

Mentor: Patricia Herterich

Welcome to OLS-2! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

Week 1 (31 August - 4 September 2020): Meet your mentor!
- [x] Create an account on [GitHub](https://github.com)
- [x] Check if you have access to the HackMD notes set up for your meetings with your mentor
- [x] Prepare to meet your mentor(s) by completing a short homework provided in the HackMD notes
- [x] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor 
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (7 - 11 September 2020): Cohort Call (Welcome to Open Life Science!)
- [x] Create an issue on the [OLS-2 GitHub repository](https://github.com/open-life-science/ols-2/issues/new) for your OLS work and share the link to your mentor.
- [x] Draft a brief vision statement using your goals

  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful

- [x] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [x] Check the [Syllabus](https://openlifesci.org/ols-2) for notes and connection info for all the cohort calls.

Before Week 3 (14 - 18 September 2020): Meet your mentor!
- [x] Look up two other projects and comment on their issues with feedback on their vision statement
- [x] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [x] Share a link to your Open Canvas in your GitHub issue
- [x] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [x] Comment on your issue with your draft Roadmap
- [x] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

Before Week 4 (21 - 25 September 2020): Cohort Call (Tooling and roadmapping for Open projects)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.

Week 5 and later
- [x] Create a GitHub repository for your project
- [x] Add the link to your repository in your issue
- [x] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [x] Link to your README in a comment on this issue
- [x] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [x] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-2 Syllabus](https://openlifesci.org/ols-2) for more detailed weekly notes and assignments past week 4.

**Comment by koudyk** [comment]
@hzahroh, this sounds super interesting! I'm also doing an education-related project. We should talk sometime. Looking forward to seeing your vision statement, canvas, etc.

**Comment by baileythegreen** [comment]
@hzahroh Will people be able to submit new materials to the platform? If so, what paths are you considering to make such contributions possible? Will the submitted materials be subjected to review first?

**Comment by malvikasharan** [comment]
@all-contributors please add @hzahroh for idea and content.

**Comment by macelik** [comment]
Is it going to be free? :)))

**Comment by hzahroh** [comment]
Hi @koudyk, thank you for stopping by. Sure, let's do that after a cohort meeting. We can exchange ideas and other things

**Comment by hzahroh** [comment]
> @hzahroh Will people be able to submit new materials to the platform? If so, what paths are you considering to make such contributions possible? Will the submitted materials be subjected to review first?

Hi @baileythegreen. Yes, definitely. One of our goals is to enable community contribution to the platform. We will provide the link to submit on our website and review them to avoid duplication to the previous content on the website.

**Comment by hzahroh** [comment]
> Is it going to be free? :)))

Hi @macelik Yes, that's also one of our goals: to make it open access.

**Comment by hzahroh** [comment]
### **Vision Statement**

APBioNetTalks is a new program of Asia Pacific Bioinformatics Network (APBioNet) to be launched in late 2020. It will serve as an online platform to host and stream bioinformatics related talks, tutorials, and training. The program aims to make the learning of bioinformatics to be more engaging, inclusive and accessible. We will invite experts, early career researchers/scientists, and Ph.D. students to share their knowledge and skills. Upon the completion of live streaming, the videos will be archived and available on-demand. This will provide community with open bioinformatics resources. In the process, we hope to promote the discovery and sharing of bioinformatics.

**Comment by hzahroh** [comment]
### **Canvas**

http://bit.ly/hilya_ols2canvas

**Comment by hzahroh** [comment]
### **Draft Roadmap**

Welcome to APBioNetTalks!
This program is a part of Asia Pacific Bioinformatics Network (APBioNet). It will serve as an online platform to host and stream bioinformatics related talks, tutorials, and training. The program aims to make the learning of bioinformatics to be more engaging, inclusive and accessible. We will invite experts, early career researchers/scientists, and Ph.D. students to share their knowledge and skills. Upon the completion of live streaming, the videos will be archived and available on-demand. This will provide community with open bioinformatics resources. In the process, we hope to promote the discovery and sharing of bioinformatics.

Video-based learning resources for bioinformatics are still scarce. Some of them are not available in English. If available, they are not free. Even if they are free, they usually only cover the introduction or very basic discussions. While most of the specific and intermediate-to-advanced discussions or skills are not accessible. This hampers the potential use of bioinformatics in solving complex biological problems. Using APBioNetTalks, we plan to solve this problem by providing open access video-based bioinformatics learning resources for the public.

#### **How to Get Involved**

**Comment by hzahroh** [comment]
### Link to APBioNetTalks Repo
https://github.com/hzahroh/APBioNetTalks

### Link to README
https://github.com/hzahroh/APBioNetTalks/blob/main/README.md
